### PR TITLE
Add ChannelSample to perf_diagnosis_demo

### PR DESCRIPTION
**Pull request by mehmetf**
This showcases a very simple platform channel implementation to test what kind of data the profiling tools provide for such calls.

Both iOS and Android implementations sleep on the platform thread for 2 seconds and send a string message back to Dart.

(Also cleaned up the unneeded ObjC files. The iOS project is based on swift)

### CODE REVIEW

**Comment by mehmetf** [comment]
@kenzieschmoll FYI

**Comment by kenzieschmoll** [comment]
Thanks for writing this up, Mehmet! I'm not sure this sample fits in this repo, however. The examples in this repo showcase performance problems. For the screens in this app, there is both a perf [problem demo](https://github.com/InMatrix/perf_diagnosis_demo/blob/master/lib/coin_flip_demo.dart) and an [optimized version](https://github.com/InMatrix/perf_diagnosis_demo/blob/master/lib/optimized/coin_flip_fix.dart) that fixes the problem.

It doesn't seem like the platform channel example fits this pattern, as it doesn't look like it has a known issue and an optimized solution. Perhaps  this would fit better added in a `platform_channel` folder inside [devtools/case_study](https://github.com/terrylucas/devtools/tree/2e8bdbdf09e3352489cea9236c36570c527afc7a/case_study).

FYI @jacob314

**Comment by mehmetf** [comment]
That's totally fine. I wanted to give you a snippet of what platform channels look like. Please feel free to move this code anywhere you would like (or just patch to your own client and test without merging).

**Comment by kenzieschmoll** [comment]
Adding to devtools/case_study in https://github.com/flutter/devtools/pull/1066

**Pull request closed without merging**
